//Generated by code: Never edit this file by hand!
package config;

import gamecontrol.*;

class Scriptcache {
	public static function localloadscript(scriptname:String):Bool {
    if (scriptname == "test") {
      s("say(msa){");
      s("	Hey, I'm Ms A!");
      s("}");
      
      s("say(mr1){");
      s("	I'm Mr 1!");
      s("}");
      
      s("say(doctoralpha){");
      s("	AND I'M DOCTOR ALPHA!!!");
      s("}");
		  return true;
    }
		return false;
  }
  
  public static function s(t:String):Void {Script.add(t);}
}
